# permissions for end users to view alertcontacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertcontact-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uptime-robot-operator
    app.kubernetes.io/part-of: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: alertcontact-viewer-role
rules:
- apiGroups:
  - uptimerobot.com
  resources:
  - alertcontacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uptimerobot.com
  resources:
  - alertcontacts/status
  verbs:
  - get
