apiVersion: uptimerobot.com/v1alpha1
kind: Account
metadata:
  labels:
    app.kubernetes.io/name: account
    app.kubernetes.io/instance: account-sample
    app.kubernetes.io/part-of: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: uptime-robot-operator
  name: account-sample
spec: {}