apiVersion: uptimerobot.com/v1alpha1
kind: Monitor
metadata:
  labels:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/instance: monitor-sample
    app.kubernetes.io/part-of: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: uptime-robot-operator
  name: monitor-sample
spec:
  # TODO(user): Add fields here
